In [2]:
import pandas as pd
import datetime

pd.set_option("display.max_rows", None)  # Show all rows
pd.set_option("display.max_columns", None)  # Show all columns
pd.set_option("display.width", None)  # No line wrapping
pd.set_option("display.colheader_justify", "center")  # Center column names


def str_to_datetime(string):
    return datetime.datetime.strptime(string, "%Y-%m-%d %H:%M:%S.%f")

def subtract_datetimes(datetime_tuple):
    return datetime_tuple[1] - datetime_tuple[0]

def subtract_datetimes_in_total_seconds(datetime_tuple):
    # print(datetime_tuple[0]>datetime_tuple[1])
    return (datetime_tuple[1] - datetime_tuple[0]).total_seconds()

def calculate_time_to_receive():
    data = pd.read_csv('Thread-0.csv')

    time_to_receive = list(map(subtract_datetimes_in_total_seconds,
                               zip(map(str_to_datetime, data['send_time'].to_list()),
                                   map(str_to_datetime, data['received_time'].to_list()))))


    data['time_to_receive'] = time_to_receive
    # print(data.)

    return data



a = calculate_time_to_receive()

In [5]:
print(len(a))

50

In [1]:
list(range(0, 19))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

In [15]:
int(a['# of message'][0])>int(a['# of message'][1])

False

In [23]:
type((1,2))

tuple

In [18]:
a

,send_time,client_id,thread_name,# of message,received_time,time_to_receive
0,2026-04-07 16:57:56.255656,malco-desktop-publisher,Thread-0,0,2026-04-07 16:57:56.255980,0.000324
1,2026-04-07 16:57:57.256234,malco-desktop-publisher,Thread-0,1,2026-04-07 16:57:57.256516,0.000282
2,2026-04-07 16:57:58.256832,malco-desktop-publisher,Thread-0,2,2026-04-07 16:57:58.257095,0.000263
3,2026-04-07 16:57:59.257481,malco-desktop-publisher,Thread-0,3,2026-04-07 16:57:59.257747,0.000266
4,2026-04-07 16:58:00.258200,malco-desktop-publisher,Thread-0,4,2026-04-07 16:58:00.258439,0.000239
5,2026-04-07 16:58:01.258559,malco-desktop-publisher,Thread-0,5,2026-04-07 16:58:01.258802,0.000243
6,2026-04-07 16:58:02.259226,malco-desktop-publisher,Thread-0,6,2026-04-07 16:58:02.259474,0.000248
7,2026-04-07 16:58:03.259806,malco-desktop-publisher,Thread-0,7,2026-04-07 16:58:03.260062,0.000256
8,2026-04-07 16:58:04.260460,malco-desktop-publisher,Thread-0,8,2026-04-07 16:58:04.260693,0.000233
9,2026-04-07 16:58:05.261055,malco-desktop-publisher,Thread-0,9,2026-04-07 16:58:05.261309,0.000254
10,2026-04-07 17:21:34.084112,malco-desktop-publisher,Thread-0,0,2026-04-07 17:21:34.084410,0.000298
11,2026-04-07 17:21:35.084850,malco-desktop-publisher,Thread-0,1,2026-04-07 17:21:35.085120,0.000270
12,2026-04-07 17:21:36.085136,malco-desktop-publisher,Thread-0,2,2026-04-07 17:21:36.085391,0.000255
13,2026-04-07 17:21:37.085481,malco-desktop-publisher,Thread-0,3,2026-04-07 17:21:37.085753,0.000272
14,2026-04-07 17:21:38.085971,malco-desktop-publisher,Thread-0,4,2026-04-07 17:21:38.086224,0.000253
15,2026-04-07 17:21:39.086637,malco-desktop-publisher,Thread-0,5,2026-04-07 17:21:39.086904,0.000267
16,2026-04-07 17:21:40.087020,malco-desktop-publisher,Thread-0,6,2026-04-07 17:21:40.087255,0.000235
17,2026-04-07 17:21:41.087553,malco-desktop-publisher,Thread-0,7,2026-04-07 17:21:41.087822,0.000269
18,2026-04-07 17:21:42.088239,malco-desktop-publisher,Thread-0,8,2026-04-07 17:21:42.088525,0.000286
19,2026-04-07 17:21:43.088677,malco-desktop-publisher,Thread-0,9,2026-04-07 17:21:43.088983,0.000306
20,2026-04-07 17:38:51.825753,malco-desktop-publisher,Thread-0,0,2026-04-07 17:38:51.826061,0.000308
21,2026-04-07 17:38:55.826235,malco-desktop-publisher,Thread-0,1,2026-04-07 17:38:55.826493,0.000258
22,2026-04-07 17:38:59.827051,malco-desktop-publisher,Thread-0,2,2026-04-07 17:38:59.827302,0.000251
23,2026-04-07 17:39:03.827495,malco-desktop-publisher,Thread-0,3,2026-04-07 17:39:03.827727,0.000232
24,2026-04-07 17:39:07.828215,malco-desktop-publisher,Thread-0,4,2026-04-07 17:39:07.828461,0.000246
25,2026-04-07 17:39:11.828773,malco-desktop-publisher,Thread-0,5,2026-04-07 17:39:11.829084,0.000311
26,2026-04-07 17:39:15.829305,malco-desktop-publisher,Thread-0,6,2026-04-07 17:39:15.829580,0.000275
27,2026-04-07 17:39:19.829702,malco-desktop-publisher,Thread-0,7,2026-04-07 17:39:19.830082,0.000380
28,2026-04-07 17:39:23.830491,malco-desktop-publisher,Thread-0,8,2026-04-07 17:39:23.830759,0.000268
29,2026-04-07 17:39:27.830881,malco-desktop-publisher,Thread-0,9,2026-04-07 17:39:27.831156,0.000275
30,2026-04-07 17:43:04.104647,malco-desktop-publisher,Thread-0,0,2026-04-07 17:43:04.104942,0.000295
31,2026-04-07 17:43:11.105578,malco-desktop-publisher,Thread-0,1,2026-04-07 17:43:11.105881,0.000303
32,2026-04-07 17:43:18.106403,malco-desktop-publisher,Thread-0,2,2026-04-07 17:43:18.106659,0.000256
33,2026-04-07 17:43:25.106987,malco-desktop-publisher,Thread-0,3,2026-04-07 17:43:25.107231,0.000244
34,2026-04-07 17:43:32.107492,malco-desktop-publisher,Thread-0,4,2026-04-07 17:43:32.107734,0.000242
35,2026-04-07 17:43:39.108280,malco-desktop-publisher,Thread-0,5,2026-04-07 17:43:39.108553,0.000273
36,2026-04-07 17:43:46.108593,malco-desktop-publisher,Thread-0,6,2026-04-07 17:43:46.108833,0.000240
37,2026-04-07 17:43:53.109375,malco-desktop-publisher,Thread-0,7,2026-04-07 17:43:53.109642,0.000267
38,2026-04-07 17:44:00.109755,malco-desktop-publisher,Thread-0,8,2026-04-07 17:44:00.110018,0.000263
39,2026-04-07 17:44:07.110297,malco-desktop-publisher,Thread-0,9,2026-04-07 17:44:07.110572,0.000275
40,2026-04-07 17:45:37.671094,malco-desktop-publisher,Thread-0,0,2026-04-07 17:45:37.671414,0.000320
41,2026-04-07 17:45:38.671502,malco-desktop-publisher,Thread-0,1,2026-04-07 17:45:38.671774,0.000272
42,2026-04-07 17:45:39.672067,malco-desktop-publisher,Thread-0,2,2026-04-07 17:45:39.672326,0.000259
43,2026-04-07 17:45:40.672313,malco-desktop-publisher,Thread-0,3,2026-04-07 17:45:40.672587,0.000274
44,2026-04-07 17:45:41.672619,malco-desktop-publisher,Thread-0,4,2026-04-07 17:45:41.672887,0.000268
45,2026-04-07 17:45:42.673283,malco-desktop-publisher,Thread-0,5,2026-04-07 17:45:42.673526,0.000243
46,2026-04-07 17:45:43.673878,malco-desktop-publisher,Thread-0,6,2026-04-07 17:45:43.674144,0.000266
47,2026-04-07 17:45:44.674615,malco-desktop-publisher,Thread-0,7,2026-04-07 17:45:44.674879,0.000264
48,2026-04-07 17:45:45.675071,malco-desktop-publisher,Thread-0,8,2026-04-07 17:45:45.675324,0.000253
49,2026-04-07 17:45:46.675612,malco-desktop-publisher,Thread-0,9,2026-04-07 17:45:46.675886,0.000274

In [20]:
list(map(int, ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12']))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [24]:
import pandas as pd
from IPython.display import display, HTML

def pretty_print(df):
    return display(HTML(df.to_html().replace("\\n","<br>")))

data = [
       {'id': 1, 't': 'very long text\ntext line 2\ntext line 3'},
       {'id': 2, 't': 'short text'}
       ]
df = pd.DataFrame(data)
df.set_index('id', inplace=True)

pretty_print(df)